#!/bin/bash -euf

if [[ $(cat node_modules/.go/VERSION || true) != "go1.18.3" ]]; then
  mkdir -p node_modules/.go
  curl -L https://go.dev/dl/go1.18.3.linux-amd64.tar.gz --output go.tmp
  sha256sum --check <(echo "956f8507b302ab0bb747613695cdae10af99bbd39a90cae522b7c0302cc27245 go.tmp")
  tar -C node_modules/.go -xzf go.tmp --strip-components=1
  rm go.tmp
fi
