#!/usr/bin/env node

/* eslint-disable @typescript-eslint/no-var-requires */

const fs = require("fs");
const prettier = require("prettier");

const tag = "<!-- PRERENDER -->";

const headEnd = "</head>";
const noindex = `<meta name="robots" content="noindex" />`;

(async () => {
  const { createServer } = require("vite");
  const vite = await createServer({
    server: { middlewareMode: true, appType: "custom" },
  });
  const { render, routes } = await vite.ssrLoadModule("/src/main-static.tsx");
  const template = fs.readFileSync("dist/index.html", "utf-8");

  if (!template.includes(tag))
    throw new Error(
      `Can't find ${tag} in dist/index.html. Was it already processed?`,
    );

  for (const url of routes) {
    const content = await render(url);
    const html = prettier.format(template.replace(tag, content), {
      parser: "html",
    });

    const path = `dist${url === "/" ? "/index" : url}.html`;
    fs.writeFileSync(path, html);
    console.log("Pre-rendered:", path);
  }

  const html = prettier.format(
    // Non-prerendered pages won't have search-friendly content and might be
    // soft 404s. Don't index.
    template.replace(tag, "").replace(headEnd, "\n" + noindex + headEnd),
    { parser: "html" },
  );
  fs.writeFileSync("dist/200.html", html);

  vite.close();
})();
