#!/bin/bash

# generates font subsets containing just the glyphs we use,
# for faster loading

set -euf -o pipefail

pyftsubset src/fonts/noto-emoji-full.woff2 \
  --unicodes="U+1F389,U+1F449,U+23F3,U+1F9ED" \
  --no-ignore-missing-unicodes \
  --layout-features="" \
  --layout-scripts="" \
  --name-IDs="" \
  --canonical-order \
  --harfbuzz-repacker \
  --flavor="woff2" \
  --output-file="src/fonts/noto-emoji.woff2"

pyftsubset src/fonts/cascadia-full.woff2 \
  --unicodes="U+0020-007E,U+2191,U+2192,U+25C6" \
  --no-ignore-missing-unicodes \
  --layout-features="" \
  --layout-scripts="" \
  --name-IDs="" \
  --canonical-order \
  --harfbuzz-repacker \
  --flavor="woff2" \
  --output-file="src/fonts/cascadia.woff2"
