#!/bin/bash

# generates font subsets containing just the glyphs we use,
# for faster loading

set -euf -o pipefail

pyftsubset "cascadia.woff2" \
  --unicodes="U+0020-007E,U+2191,U+2192,U+25C6" \
  --no-ignore-missing-unicodes \
  --layout-features="" \
  --layout-scripts="" \
  --name-IDs="0,13,14" \
  --canonical-order \
  --harfbuzz-repacker \
  --flavor="woff2" \
  --output-file="cascadia-subset.woff2"

pyftsubset "noto-emoji.woff2" \
  --unicodes="U+1F389,U+1F449,U+23F3,U+1F9ED" \
  --no-ignore-missing-unicodes \
  --layout-features="" \
  --layout-scripts="" \
  --name-IDs="0,13,14" \
  --canonical-order \
  --harfbuzz-repacker \
  --flavor="woff2" \
  --output-file="noto-emoji-subset.woff2"

pyftsubset "plex-mono.woff2" \
  --unicodes="U+0020-007E" \
  --no-ignore-missing-unicodes \
  --layout-features="" \
  --layout-scripts="" \
  --name-IDs="0,13,14" \
  --canonical-order \
  --harfbuzz-repacker \
  --flavor="woff2" \
  --output-file="plex-mono-subset.woff2"
